In [1]:
import numpy as np

# Fuzzy string matching

Interview question.

Taken from https://www.datacamp.com/community/tutorials/fuzzy-string-python, few things removed, computes Levenshtein distance between two strings.

In [28]:
def levenshtein_distance(s, t):
    """ levenshtein_distance:
        Calculates levenshtein distance between two strings.
        For all i and j, distance[i,j] will contain the Levenshtein
        distance between the first i characters of s and the
        first j characters of t
    """
    rows = len(s)+1
    cols = len(t)+1
    distance = np.zeros((rows,cols),dtype = int)

    # if one string is zero length, then the distance from the other string is equal to the length of the other string (true for every substring)
    # indeed if both are zero length, the distance is zero.
    for row in range(rows):
        distance[row][0] = row
        for col in range(1,cols):
            if row == 0:
                distance[row][col] = col
            else:
                cost = 0 if s[row-1] == t[col-1] else 1
                distance[row][col] = min(distance[row-1][col] + 1,      # Cost of deletions
                                     distance[row][col-1] + 1,          # Cost of insertions
                                     distance[row-1][col-1] + cost)

    print(distance)
    return distance[len(s)][len(t)]

In [29]:
levenshtein_distance("ad","trac")

[[0 1 2 3 4]
 [1 1 2 2 3]
 [2 2 2 3 3]]


3